#pragma once
#include <stdint.h>
#include <vector>
#include <string>
#include <boost/utility/string_view.hpp>
#include "QTSS.h"
namespace ServerPrefs {
	uint32_t GetSafePlayDurationInSecs();
	uint32_t GetTotalBytesUpdateTimeInSecs();
	uint32_t GetRTCPSocketRcvBufSizeinK();
	uint32_t GetAvgBandwidthUpdateTimeInSecs();
	bool GetAllowGuestDefault();
	boost::string_view GetAuthorizationRealm();
	bool IsSlowStartEnabled();
	uint32_t GetRTPSessionTimeoutInSecs();
	uint32_t GetSendIntervalInMsec();
	float GetOverbufferRate();
	uint16_t GetDefaultStreamQuality();
	uint32_t GetWindowSizeMaxThreshold();
	uint32_t GetLargeWindowSizeInK();
	uint32_t GetWindowSizeThreshold();
	uint32_t GetMediumWindowSizeInK();
	uint32_t GetSmallWindowSizeInK();
	int32_t  GetMaxKBitsBandwidth();
	uint32_t GetMaxRetransmitDelayInMsec();
	uint32_t GetMaxSendAheadTimeInSecs();
	uint32_t GetMaxTCPBufferSizeInBytes();
	uint32_t GetMinTCPBufferSizeInBytes();
	int32_t GetDropAllPacketsTimeInMsec();
	uint32_t GetRTSPSessionTimeoutInSecs();
	boost::string_view GetTransportSrcAddr();
	float GetTCPSecondsToBuffer();
	boost::string_view GetMovieFolder();
	std::vector<std::string> GetReqRTPStartTimeAdjust();
}